language: go

os:
  - linux
  - osx
  - windows

go:
  - 1.13.x
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

env:
  - GO111MODULE=on

before_install:
  - go get github.com/spf13/cobra
  - go get github.com/spf13/viper
  - go get go.uber.org/zap
  - go get github.com/mitchellh/go-homedir

before_script:
  - make build

script:
  - make test-verbose
